"use client";

import {
  BadgeDollarSign,
  BrainCircuit,
  Briefcase,
  Car,
  ChartColumn,
  CircleDollarSign,
  Coins,
  Compass,
  CreditCard,
  Crosshair,
  Dice5,
  Dumbbell,
  Gamepad2,
  Gauge,
  Gift,
  Globe,
  KeyRound,
  Medal,
  MessageCircle,
  Monitor,
  Package,
  Shield,
  Skull,
  Smartphone,
  Sword,
  Swords,
  Target,
  Trophy,
  Video,
  Wallet,
  Wrench,
} from "lucide-react";
import {
  FaAmazon,
  FaAndroid,
  FaApple,
  FaPaypal,
  FaPlaystation,
  FaWindows,
  FaXbox,
} from "react-icons/fa";
import {
  SiBattledotnet,
  SiDiscord,
  SiEa,
  SiEpicgames,
  SiPaypal,
  SiPubg,
  SiRiotgames,
  SiRoblox,
  SiSpotify,
  SiSteam,
  SiUbisoft,
  SiValorant,
  SiYoutube,
} from "react-icons/si";
import {
  CategoryLandingClient,
  type LandingCategory,
} from "./CategoryLandingClient";

export type MarketplaceCategoryPageKey =
  | "pc-games"
  | "mobile"
  | "game-currency"
  | "game-accounts"
  | "game-items"
  | "power-leveling"
  | "software"
  | "gift-cards"
  | "game-cards";

type MarketplaceCategoryPageConfig = {
  title: string;
  description: string;
  categories: LandingCategory[];
  showMore?: boolean;
  paginationPages?: string[];
};

const genreImages = {
  shooter: "/battlefield_6.jpg",
  mmorpg: "/bg-category-hero-pc.jpg",
  adventure: "/bg-category-services.jpg",
  simulator: "/topup-delta-force.jpg",
  sport: "/bg-category-mobile.jpg",
  action: "/cyberpunk_2077.jpg",
  rpg: "/bg-category-all-categories.jpg",
  fighting: "/product2.jpg",
  survival: "/bg-category-hero-console.jpg",
  mmo: "/topup-imo.jpg",
  hackSlash: "/bg4.webp",
  racing: "/banner-item.webp",
  strategy: "/bg-category-hero-gift.jpg",
} as const;

const genreTones = {
  shooter: "from-[#242b35]/80 via-[#323846]/74 to-[#222936]/84",
  mmorpg: "from-[#25596c]/80 via-[#1f4b62]/76 to-[#20334a]/88",
  adventure: "from-[#263347]/82 via-[#29394f]/76 to-[#394047]/84",
  simulator: "from-[#332f2d]/80 via-[#34465b]/76 to-[#1d2838]/84",
  sport: "from-[#2b5048]/80 via-[#2d4450]/76 to-[#253248]/86",
  action: "from-[#352b4c]/82 via-[#3b3248]/76 to-[#2a2e3c]/86",
  rpg: "from-[#323237]/82 via-[#27303d]/76 to-[#1f2835]/86",
  fighting: "from-[#27365a]/82 via-[#263247]/76 to-[#202936]/86",
  survival: "from-[#314541]/82 via-[#283746]/76 to-[#202936]/86",
  mmo: "from-[#514238]/82 via-[#3f3940]/76 to-[#242e39]/86",
  hackSlash: "from-[#34362f]/82 via-[#27313b]/76 to-[#1f2834]/86",
  racing: "from-[#554035]/82 via-[#3d313a]/76 to-[#252d39]/86",
  strategy: "from-[#40372d]/82 via-[#30313a]/76 to-[#222a35]/86",
} as const;

const gameGenreCategories: LandingCategory[] = [
  {
    name: "Shooter",
    products: "14 products",
    filterId: "shooter",
    href: "/product?category=shooter",
    icon: Crosshair,
    image: genreImages.shooter,
    tone: genreTones.shooter,
  },
  {
    name: "MMORPG",
    products: "90 products",
    filterId: "mmorpg",
    href: "/product?category=mmorpg",
    icon: KeyRound,
    image: genreImages.mmorpg,
    tone: genreTones.mmorpg,
  },
  {
    name: "Adventure",
    products: "11 products",
    filterId: "adventure",
    href: "/product?category=adventure",
    icon: Compass,
    image: genreImages.adventure,
    tone: genreTones.adventure,
  },
  {
    name: "Simulator",
    products: "13 products",
    filterId: "simulator",
    href: "/product?category=simulator",
    icon: Gamepad2,
    image: genreImages.simulator,
    tone: genreTones.simulator,
  },
  {
    name: "Sport",
    products: "5 products",
    filterId: "sport",
    href: "/product?category=sport",
    icon: Dumbbell,
    image: genreImages.sport,
    tone: genreTones.sport,
  },
  {
    name: "Action",
    products: "36 products",
    filterId: "action",
    href: "/product?category=action",
    icon: Swords,
    image: genreImages.action,
    tone: genreTones.action,
  },
  {
    name: "RPG",
    products: "4 products",
    filterId: "rpg",
    href: "/product?category=rpg",
    icon: Gauge,
    image: genreImages.rpg,
    tone: genreTones.rpg,
  },
  {
    name: "Fighting",
    products: "4 products",
    filterId: "fighting",
    href: "/product?category=fighting",
    icon: Trophy,
    image: genreImages.fighting,
    tone: genreTones.fighting,
  },
  {
    name: "Survival horror",
    products: "5 products",
    filterId: "survival-horror",
    href: "/product?category=survival-horror",
    icon: Skull,
    image: genreImages.survival,
    tone: genreTones.survival,
  },
  {
    name: "MMO",
    products: "4 products",
    filterId: "mmo",
    href: "/product?category=mmo",
    icon: Gamepad2,
    image: genreImages.mmo,
    tone: genreTones.mmo,
  },
  {
    name: "Hack and Slash",
    products: "15 products",
    filterId: "hack-and-slash",
    href: "/product?category=hack-and-slash",
    icon: Sword,
    image: genreImages.hackSlash,
    tone: genreTones.hackSlash,
  },
  {
    name: "Racing",
    products: "1 products",
    filterId: "racing",
    href: "/product?category=racing",
    icon: Car,
    image: genreImages.racing,
    tone: genreTones.racing,
  },
  {
    name: "Strategy",
    products: "11 products",
    filterId: "strategy",
    href: "/product?category=strategy",
    icon: Medal,
    image: genreImages.strategy,
    tone: genreTones.strategy,
  },
];

const pageConfigs: Record<
  MarketplaceCategoryPageKey,
  MarketplaceCategoryPageConfig
> = {
  "pc-games": {
    title: "PC Games",
    description:
      "At Difmark marketplace you can buy accounts convenient for you platform with your favourite game. Only on Difmark at the cheapest prices.",
    categories: [
      {
        name: "Steam",
        products: "9 668 products",
        filterId: "steam",
        href: "/product?platform=steam",
        icon: SiSteam,
        tone: "from-[#263c5c]/94 via-[#213553]/90 to-[#1a293d]/92",
      },
      {
        name: "Epic Games",
        products: "1 429 products",
        filterId: "epic-games",
        href: "/product?platform=epic",
        icon: SiEpicgames,
        image: "/bg-category-hero-console.jpg",
        tone: "from-[#6a523e]/88 via-[#5f4a45]/84 to-[#56323d]/90",
      },
      {
        name: "Windows Store",
        products: "277 products",
        filterId: "windows-store",
        href: "/product?platform=windows-store",
        icon: FaWindows,
        tone: "from-[#392967]/92 via-[#25265b]/90 to-[#133246]/92",
      },
      {
        name: "Electronic Arts",
        products: "47 products",
        filterId: "electronic-arts",
        href: "/product?platform=ea",
        icon: SiEa,
        image: "/bg-category-all-categories.jpg",
        tone: "from-[#535862]/84 via-[#4b5360]/78 to-[#343d4a]/88",
      },
      {
        name: "Ubisoft",
        products: "25 products",
        filterId: "ubisoft",
        href: "/product?platform=ubisoft",
        icon: SiUbisoft,
        image: "/bg-category-services.jpg",
        tone: "from-[#273547]/88 via-[#243145]/84 to-[#1d2738]/90",
      },
      {
        name: "Battlenet",
        products: "1 products",
        filterId: "battlenet",
        href: "/product?platform=battle-net",
        icon: SiBattledotnet,
        image: "/bg-category-hero-pc.jpg",
        tone: "from-[#223a56]/90 via-[#213550]/86 to-[#1b2b41]/92",
      },
    ],
  },
  mobile: {
    title: "Mobile",
    description:
      "Only on Difmark Marketplace you can find your favorite ios and android programs or games at the cheapest prices.",
    categories: [
      {
        name: "IOS",
        products: "54 products",
        filterId: "ios",
        href: "/product?platform=ios",
        icon: FaApple,
        image: "/category-hero-mobile.webp",
        tone: "from-[#7d3d3d]/88 via-[#65545f]/82 to-[#1e3d6c]/90",
      },
      {
        name: "Android",
        products: "56 products",
        filterId: "android",
        href: "/product?platform=android",
        icon: FaAndroid,
        tone: "from-[#2d6a73]/88 via-[#3c685e]/86 to-[#425a37]/90",
      },
    ],
  },
  "game-currency": {
    title: "Game Currency",
    description:
      "Explore gaming wealth with buying gaming currency on Difmark! Unlock unprecedented currency deals like gold, silver and more. Raise your gaming experience without much effort, trade for free and plunge into the world of plenty of games",
    categories: gameGenreCategories,
  },
  "game-accounts": {
    title: "Game Accounts",
    description:
      "Save cash on games by buying accounts! It's totally legit, safe, and super convenient. No need to shell out extra for your favorite gaming goodies - we've got you covered with the best deals around.",
    categories: gameGenreCategories.map((category) => ({
      ...category,
      products:
        {
          MMORPG: "53 products",
          Shooter: "12 products",
          Adventure: "4 products",
          Action: "31 products",
          Sport: "4 products",
          RPG: "4 products",
          Racing: "1 products",
          Fighting: "2 products",
          "Hack and Slash": "12 products",
          Simulator: "8 products",
          Strategy: "10 products",
          "Survival horror": "5 products",
        }[category.name] ?? category.products,
    })),
  },
  "game-items": {
    title: "Game Items",
    description:
      "Unlock endless game items with Difmark! Dive into exclusive deals from trusted sellers worldwide. Enhance your gaming journey with ease and excellence.",
    categories: gameGenreCategories.map((category) => ({
      ...category,
      products:
        {
          Shooter: "11 products",
          MMORPG: "53 products",
          Action: "33 products",
          "Hack and Slash": "12 products",
          Simulator: "7 products",
          RPG: "4 products",
          Adventure: "4 products",
          Sport: "4 products",
          Racing: "1 products",
          Fighting: "2 products",
          Strategy: "10 products",
          "Survival horror": "5 products",
          MMO: "1 products",
        }[category.name] ?? category.products,
    })),
  },
  "power-leveling": {
    title: "Power Leveling",
    description:
      "Supercharge your leveling experience with Difmark - acquire pre-made accounts quickly and affordably. Rely on us to ensure the safest transactions, reputable independent sellers, and a variety of accounts tailored to your preferences.",
    categories: gameGenreCategories.map((category) => ({
      ...category,
      products:
        {
          Shooter: "11 products",
          MMORPG: "51 products",
          MMO: "1 products",
          "Hack and Slash": "12 products",
          RPG: "4 products",
          Fighting: "2 products",
          "Survival horror": "5 products",
          Action: "32 products",
          Sport: "3 products",
          Simulator: "7 products",
          Racing: "1 products",
          Adventure: "4 products",
          Strategy: "10 products",
        }[category.name] ?? category.products,
    })),
  },
  software: {
    title: "Software",
    description:
      "Buy and enjoy the latest versions of software together with the Difmark. With us you will find what you need for work or hobbies at the lowest prices.",
    categories: [
      {
        name: "Microsoft",
        products: "163 products",
        filterId: "microsoft",
        href: "/product?category=microsoft",
        icon: FaWindows,
        tone: "from-[#422d72]/92 via-[#24305c]/88 to-[#16344a]/92",
      },
      {
        name: "Performance",
        products: "156 products",
        filterId: "performance",
        href: "/product?category=performance",
        icon: ChartColumn,
        image: "/category-hero-software1.webp",
        tone: "from-[#273a57]/88 via-[#1e314e]/84 to-[#19283d]/92",
      },
      {
        name: "Antivirus",
        products: "102 products",
        filterId: "antivirus",
        href: "/product?category=antivirus",
        icon: Shield,
        image: "/category-hero-software2.webp",
        tone: "from-[#2f2c68]/88 via-[#253456]/82 to-[#1e3048]/90",
      },
      {
        name: "VPN",
        products: "31 products",
        filterId: "vpn",
        href: "/product?category=vpn",
        icon: KeyRound,
        image: "/bg-category-hero-software.jpg",
        tone: "from-[#263a57]/88 via-[#25364d]/82 to-[#1f2d40]/90",
      },
      {
        name: "Security",
        products: "117 products",
        filterId: "security",
        href: "/product?category=security",
        icon: Globe,
        image: "/bg-category-services.jpg",
        tone: "from-[#32294f]/88 via-[#20314c]/82 to-[#1d2b3e]/90",
      },
      {
        name: "Gaming/Video",
        products: "245 products",
        filterId: "gaming-video",
        href: "/product?category=gaming-video",
        icon: Gamepad2,
        image: "/bg4.webp",
        tone: "from-[#5b315c]/88 via-[#443255]/82 to-[#203047]/90",
      },
      {
        name: "Ashampoo",
        products: "64 products",
        filterId: "ashampoo",
        href: "/product?category=ashampoo",
        icon: Monitor,
        image: "/category-hero-software2.webp",
        tone: "from-[#38447a]/84 via-[#39566c]/78 to-[#2c3a48]/88",
      },
      {
        name: "NCH Software",
        products: "23 products",
        filterId: "nch-software",
        href: "/product?category=nch-software",
        icon: Video,
        image: "/bg3.webp",
        tone: "from-[#30343d]/88 via-[#2b303b]/82 to-[#1f2834]/90",
      },
      {
        name: "Project Softwares",
        products: "11 products",
        filterId: "project-softwares",
        href: "/product?category=project-softwares",
        icon: Briefcase,
        image: "/bg-category-hero-pc.jpg",
        tone: "from-[#315a79]/88 via-[#294b66]/84 to-[#223648]/90",
      },
      {
        name: "Website builder",
        products: "7 products",
        filterId: "website-builder",
        href: "/product?category=website-builder",
        icon: Wrench,
        image: "/bg-category-hero-gift.jpg",
        tone: "from-[#60452b]/88 via-[#384257]/82 to-[#1e2d3e]/90",
      },
      {
        name: "Movavi",
        products: "33 products",
        filterId: "movavi",
        href: "/product?category=movavi",
        icon: Package,
        image: "/bg2.webp",
        tone: "from-[#20306d]/88 via-[#253153]/82 to-[#1f2a3b]/90",
      },
      {
        name: "SnagIt",
        products: "1 products",
        filterId: "snagit",
        href: "/product?category=snagit",
        icon: CreditCard,
        image: "/category-hero-services2.webp",
        tone: "from-[#344658]/88 via-[#29384a]/82 to-[#1f2b3b]/90",
      },
      {
        name: "AI Tools",
        products: "2 products",
        filterId: "ai-tools",
        href: "/product?category=ai-tools",
        icon: BrainCircuit,
        image: "/category-hero-services1.webp",
        tone: "from-[#233759]/88 via-[#1e2d4a]/84 to-[#1a273b]/90",
      },
      {
        name: "Apple",
        products: "7 products",
        filterId: "apple",
        href: "/product?category=apple",
        icon: FaApple,
        image: "/category-hero-mobile.webp",
        tone: "from-[#2a4156]/88 via-[#263746]/84 to-[#1e2a38]/90",
      },
      {
        name: "Franzis",
        products: "7 products",
        filterId: "franzis",
        href: "/product?category=franzis",
        icon: Package,
        image: "/bg1.webp",
        tone: "from-[#323640]/88 via-[#2a303b]/84 to-[#202936]/90",
      },
      {
        name: "Finance",
        products: "2 products",
        filterId: "finance",
        href: "/product?category=finance",
        icon: Wallet,
        image: "/sale1.webp",
        tone: "from-[#514430]/88 via-[#373747]/82 to-[#1f2a38]/90",
      },
    ],
  },
  "gift-cards": {
    title: "Gift Cards",
    description:
      "Discover endless possibilities with Difmark! Our gift cards will give you an unforgettable gaming experience and serve as a nice bonus to your gameplay.",
    showMore: true,
    paginationPages: ["1", "2", "3", "4", "5", "6", "7", "47"],
    categories: [
      {
        name: "SkinRave gg",
        products: "9 products",
        filterId: "skinrave",
        href: "/product?category=skinrave",
        icon: Target,
        image: "/category-hero-gift1.webp",
        tone: "from-[#315c4b]/88 via-[#34474a]/82 to-[#1f2f3e]/90",
      },
      {
        name: "PLG BET",
        products: "9 products",
        filterId: "plg-bet",
        href: "/product?category=plg-bet",
        icon: Dice5,
        image: "/bg-category-hero-gift.jpg",
        tone: "from-[#2f3547]/88 via-[#32364b]/82 to-[#1e2a3b]/90",
      },
      {
        name: "Gamblit",
        products: "6 products",
        filterId: "gamblit",
        href: "/product?category=gamblit",
        icon: BadgeDollarSign,
        image: "/category-hero-services5.webp",
        tone: "from-[#232c3d]/88 via-[#273142]/82 to-[#1f2938]/90",
      },
      {
        name: "CSGORUN",
        products: "9 products",
        filterId: "csgorun",
        href: "/product?category=csgorun",
        icon: Swords,
        image: "/bg4.webp",
        tone: "from-[#243b63]/88 via-[#23334f]/82 to-[#202a3d]/90",
      },
      {
        name: "KNIFEX",
        products: "7 products",
        filterId: "knifex",
        href: "/product?category=knifex",
        icon: Swords,
        image: "/category-hero-gift2.webp",
        tone: "from-[#3f3569]/88 via-[#2a344c]/82 to-[#202a3b]/90",
      },
      {
        name: "YouTube",
        products: "10 products",
        filterId: "youtube",
        href: "/product?category=youtube",
        icon: SiYoutube,
        image: "/bg-category-hero-console.jpg",
        tone: "from-[#753839]/88 via-[#62313a]/82 to-[#3e2836]/90",
      },
      {
        name: "TastyDrop",
        products: "7 products",
        filterId: "tastydrop",
        href: "/product?category=tastydrop",
        icon: Gift,
        image: "/category-hero-gift3.webp",
        tone: "from-[#332e67]/88 via-[#2f365d]/82 to-[#223044]/90",
      },
      {
        name: "Discord",
        products: "53 products",
        filterId: "discord",
        href: "/product?category=discord",
        icon: SiDiscord,
        image: "/topup-sugo-voice-live-chat.jpg",
        tone: "from-[#2f3e8a]/88 via-[#2e3a70]/82 to-[#232e54]/90",
      },
      {
        name: "Bets4",
        products: "5 products",
        filterId: "bets4",
        href: "/product?category=bets4",
        icon: ChartColumn,
        tone: "from-[#26313f]/90 via-[#242e3b]/88 to-[#1f2936]/92",
      },
      {
        name: "TastyStrike",
        products: "7 products",
        filterId: "tastystrike",
        href: "/product?category=tastystrike",
        icon: Gift,
        image: "/category-hero-gift3.webp",
        tone: "from-[#26315e]/88 via-[#263153]/82 to-[#1f2a3d]/90",
      },
      {
        name: "Telegram",
        products: "16 products",
        filterId: "telegram",
        href: "/product?category=telegram",
        icon: MessageCircle,
        image: "/category-hero-mobile.webp",
        tone: "from-[#5b6873]/88 via-[#4b5965]/82 to-[#364655]/90",
      },
      {
        name: "Steam",
        products: "1 516 products",
        filterId: "steam",
        href: "/product?platform=steam",
        icon: SiSteam,
        tone: "from-[#253c61]/92 via-[#223653]/88 to-[#1b2d45]/92",
      },
      {
        name: "Playstation",
        products: "354 products",
        filterId: "playstation",
        href: "/product?platform=playstation",
        icon: FaPlaystation,
        image: "/bg-category-hero-console.jpg",
        tone: "from-[#263d76]/90 via-[#243863]/86 to-[#1d2f4b]/92",
      },
      {
        name: "Xbox Live",
        products: "243 products",
        filterId: "xbox-live",
        href: "/product?platform=xbox",
        icon: FaXbox,
        image: "/bg-category-hero-console.jpg",
        tone: "from-[#3e6a45]/90 via-[#315a3c]/86 to-[#244333]/92",
      },
      {
        name: "Amazon",
        products: "714 products",
        filterId: "amazon",
        href: "/product?category=amazon",
        icon: FaAmazon,
        image: "/sale1.webp",
        tone: "from-[#2b2f3a]/88 via-[#453529]/82 to-[#1e2938]/90",
      },
      {
        name: "DaddySkins",
        products: "16 products",
        filterId: "daddyskins",
        href: "/product?category=daddyskins",
        icon: Skull,
        image: "/bg3.webp",
        tone: "from-[#302c73]/88 via-[#283153]/82 to-[#1f2a3b]/90",
      },
      {
        name: "Difmark",
        products: "22 products",
        filterId: "difmark",
        href: "/product?category=difmark",
        icon: Gift,
        tone: "from-[#2f5d42]/90 via-[#254637]/86 to-[#1d2d32]/92",
      },
      {
        name: "Spotify",
        products: "27 products",
        filterId: "spotify",
        href: "/product?category=spotify",
        icon: SiSpotify,
        tone: "from-[#3c7c4e]/90 via-[#36714a]/86 to-[#2b5b41]/92",
      },
      {
        name: "Disney",
        products: "109 products",
        filterId: "disney",
        href: "/product?category=disney",
        icon: Gift,
        image: "/hero-slide-1.webp",
        tone: "from-[#25395b]/88 via-[#27334f]/82 to-[#202a3d]/90",
      },
      {
        name: "PayPal",
        products: "560 products",
        filterId: "paypal",
        href: "/product?category=paypal",
        icon: SiPaypal,
        tone: "from-[#2d6b95]/90 via-[#26547f]/86 to-[#1f3a5f]/92",
      },
    ],
  },
  "game-cards": {
    title: "Game Cards",
    description:
      "Dive into the world of gaming abundance with Game Points! Discover unbeatable deals on virtual currencies and points to enhance your gaming experience. Explore the possibilities and make every game session memorable!",
    showMore: true,
    paginationPages: ["1", "2", "3", "4"],
    categories: [
      {
        name: "Roblox",
        products: "523 products",
        filterId: "roblox",
        href: "/product?category=roblox",
        icon: SiRoblox,
        image: "/topup-afk-journey.jpg",
        tone: "from-[#2e3f52]/88 via-[#29354b]/82 to-[#1f2a3b]/90",
      },
      {
        name: "FIFA FUT Points",
        products: "80 products",
        filterId: "fifa-fut-points",
        href: "/product?category=fifa-fut-points",
        icon: SiEa,
        image: "/topup-ea-sports-fc-mobile.jpg",
        tone: "from-[#20354d]/88 via-[#24334a]/82 to-[#1f2a39]/90",
      },
      {
        name: "PUBG Mobile",
        products: "20 products",
        filterId: "pubg-mobile",
        href: "/product?category=pubg-mobile",
        icon: SiPubg,
        image: "/topup-pubg.jpg",
        tone: "from-[#576069]/88 via-[#3f4f5d]/82 to-[#2d3c4c]/90",
      },
      {
        name: "IMVU",
        products: "17 products",
        filterId: "imvu",
        href: "/product?category=imvu",
        icon: Smartphone,
        image: "/topup-chamet.jpg",
        tone: "from-[#536a72]/88 via-[#435763]/82 to-[#2f4050]/90",
      },
      {
        name: "Lotro",
        products: "2 products",
        filterId: "lotro",
        href: "/product?category=lotro",
        icon: Shield,
        image: "/bg-category-hero-pc.jpg",
        tone: "from-[#373944]/88 via-[#2d3440]/82 to-[#202b39]/90",
      },
      {
        name: "LOL",
        products: "173 products",
        filterId: "lol",
        href: "/product?category=lol",
        icon: SiRiotgames,
        image: "/topup-honor-of-kings.jpg",
        tone: "from-[#27324d]/88 via-[#263149]/82 to-[#202a3b]/90",
      },
      {
        name: "Free Fire",
        products: "18 products",
        filterId: "free-fire",
        href: "/product?category=free-fire",
        icon: Crosshair,
        image: "/topup-free-fire.jpg",
        tone: "from-[#334b61]/88 via-[#2d3f54]/82 to-[#213044]/90",
      },
      {
        name: "Valorant",
        products: "252 products",
        filterId: "valorant",
        href: "/product?category=valorant",
        icon: SiValorant,
        image: "/topup-valorant.jpg",
        tone: "from-[#462f45]/88 via-[#372f45]/82 to-[#222b3b]/90",
      },
      {
        name: "Diablo IV",
        products: "5 products",
        filterId: "diablo-iv",
        href: "/product?category=diablo-iv",
        icon: Skull,
        tone: "from-[#242e3c]/92 via-[#222b38]/88 to-[#1e2734]/92",
      },
      {
        name: "Minecraft",
        products: "8 products",
        filterId: "minecraft",
        href: "/product?category=minecraft",
        icon: Package,
        image: "/bg-category-all-categories.jpg",
        tone: "from-[#555537]/88 via-[#424833]/82 to-[#28333a]/90",
      },
      {
        name: "FC Mobile Points",
        products: "7 products",
        filterId: "fc-mobile-points",
        href: "/product?category=fc-mobile-points",
        icon: CircleDollarSign,
        tone: "from-[#232d3b]/92 via-[#222b38]/88 to-[#1e2734]/92",
      },
      {
        name: "Mobile Legends",
        products: "83 products",
        filterId: "mobile-legends",
        href: "/product?category=mobile-legends",
        icon: Sword,
        tone: "from-[#232d3b]/92 via-[#222b38]/88 to-[#1e2734]/92",
      },
      {
        name: "CSGO",
        products: "16 products",
        filterId: "csgo",
        href: "/product?category=csgo",
        icon: Crosshair,
        image: "/category-hero-gift1.webp",
        tone: "from-[#554336]/88 via-[#3e3a3d]/82 to-[#202b39]/90",
      },
      {
        name: "Overwatch 2",
        products: "9 products",
        filterId: "overwatch-2",
        href: "/product?category=overwatch-2",
        icon: Target,
        image: "/hero-slide-2.webp",
        tone: "from-[#384461]/88 via-[#303b54]/82 to-[#222d3f]/90",
      },
      {
        name: "EA SPORTS College Football Poi",
        products: "5 products",
        filterId: "ea-sports-college-football",
        href: "/product?category=ea-sports-college-football",
        icon: Coins,
        image: "/topup-ea-sports-fc-mobile.jpg",
        tone: "from-[#584239]/88 via-[#3d3842]/82 to-[#222c3d]/90",
      },
      {
        name: "Candy Crush",
        products: "25 products",
        filterId: "candy-crush",
        href: "/product?category=candy-crush",
        icon: Gift,
        tone: "from-[#232d3b]/92 via-[#222b38]/88 to-[#1e2734]/92",
      },
      {
        name: "NetDragon Universal",
        products: "2 products",
        filterId: "netdragon-universal",
        href: "/product?category=netdragon-universal",
        icon: Globe,
        tone: "from-[#232d3b]/92 via-[#222b38]/88 to-[#1e2734]/92",
      },
      {
        name: "Dead by Daylight Golden Cells",
        products: "5 products",
        filterId: "dead-by-daylight-golden-cells",
        href: "/product?category=dead-by-daylight-golden-cells",
        icon: Skull,
        image: "/bg-time-sale.webp",
        tone: "from-[#313343]/88 via-[#313444]/82 to-[#222c3b]/90",
      },
      {
        name: "Lawl Online",
        products: "5 products",
        filterId: "lawl-online",
        href: "/product?category=lawl-online",
        icon: Coins,
        image: "/topup-magic-chess-go-go.jpg",
        tone: "from-[#2d4e61]/88 via-[#294354]/82 to-[#213244]/90",
      },
      {
        name: "Halo Infinite Halo Credits",
        products: "5 products",
        filterId: "halo-infinite-halo-credits",
        href: "/product?category=halo-infinite-halo-credits",
        icon: CreditCard,
        tone: "from-[#232d3b]/92 via-[#222b38]/88 to-[#1e2734]/92",
      },
    ],
  },
};

export function MarketplaceCategoryPageClient({
  pageKey,
}: {
  pageKey: MarketplaceCategoryPageKey;
}) {
  const pageConfig = pageConfigs[pageKey];

  return (
    <CategoryLandingClient
      title={pageConfig.title}
      description={pageConfig.description}
      categories={pageConfig.categories}
      searchInputId={`${pageKey}-category-search`}
      showMore={pageConfig.showMore}
      paginationPages={pageConfig.paginationPages}
      productTypeFilterId={pageKey}
    />
  );
}
